- .github/workflows/publish.yml
This PR offers the possibility to publish a the `.phar` within the release the assets, everytime a release is created
cf. https://github.com/laravel/pint/issues/28
> [0.x] Publish PHAR

- .github/workflows/publish-phar.yml
This PR fixes the actions versions for the PHAR deployment job.
> Fix actions versions for PHAR deployment job.

- .github/workflows/publish-phar.yml
This PR fixes the tax version extraction.
> Fix the tax version extraction.

- .github/workflows/publish-phar.yml
Use `actions/upload-artifact` to upload the phar
> [1.x] Use actions/upload-artifact

- resources/presets/laravel.php
> Revert "[1.x] Update `method_argument_space rule` in Laravel preset"

- app/Repositories/GitPathsRepository.php
This handles what I believe is the proper filtering of _deleted_ and _renamed_files based on the standard output of `git status --short`. It does so with PHP to limit the underlying system dependencies to just `git`.
> Filter deleted and renamed files

- composer.json
- composer.lock
This pull request makes Pint to use PHP CS Fixer `^3.16.0`.
> [1.x] Makes Pint to use PHP CS Fixer `^3.16.0`.

- README.md
> Fix overview image on packagist.org

- resources/presets/laravel.php
> Enable method_chaining_indentation fixer

- resources/presets/laravel.php
> Enable statement_indentation rule in Laravel preset

- app/Actions/ElaborateSummary.php
- resources/presets/laravel.php
- tests/Feature/Fixers/YodaStyleFixerTest.php
- tests/Fixtures/fixers/yoda_style.php
This pull request fixes non yoda style moving variables.
Fixes: https://github.com/laravel/pint/pull/210#issuecomment-1707446079.
> [1.x] Fixes non yoda style moving variables

- composer.json
- composer.lock
This pull requests increase Pint's internal dependencies.
> [1.x] Increases dependencies

- composer.json
- composer.lock
- resources/presets/laravel.php
- tests/Feature/SummaryTest.php
> [1.x] Replace deprecated rules

- composer.json
- composer.lock
This pull request makes Pint to use `"friendsofphp/php-cs-fixer": "^3.38.0"`.
> [1.x] Uses `"friendsofphp/php-cs-fixer": "^3.38.0"`

- composer.json
- composer.lock
- phpstan.neon
Abandoned warning
`Package nunomaduro/larastan is abandoned, you should avoid using it. Use larastan/larastan instead.`
> Upgrade to larastan/larastan

- composer.json
- composer.lock
Updates `composer.json` dependencies.
> [1.x] Bumps dependencies

- composer.json
- composer.lock
Some small updates to the dependencies.
(Includes bugfixes from PHP-CS-Fixer, though I have encountered no specific problem yet).
> [1.x] Bump dependencies

- app/Output/SummaryOutput.php
It seems that the list of presets should be updated here so that the empty preset can work.
> Add empty preset to the list

- app/Exceptions/HandleExceptions.php
- bootstrap/app.php
- composer.lock
> Hides PHP 8.4 Deperecation Warning

- composer.json
- composer.lock
> Bump dependencies (php-cs-fixer fixes)

- overrides/Runner/Parallel/ProcessFactory.php
This PR fixes `--parallel` in windows.
> fix: parallel in windows
