- app/Factories/ConfigurationFactory.php
This will ignore the `_ide_helper_models.php` file which also can be generated with `barryvdh/laravel-ide-helper`.
> Ignore _ide_helper_models.php

- app/Factories/ConfigurationFactory.php
This PR simply ignores `.phpstorm.meta.php` which is generated by PhpStorm automatically when using barryvdh/laravel-ide-helper: https://github.com/barryvdh/laravel-ide-helper#phpstorm-meta-for-container-instances
> Ignore .phpstorm.meta.php

- app/Factories/ConfigurationFactory.php
- app/Fixers/LaravelPhpdocAlignmentFixer.php
- app/Fixers/LaravelPhpdocOrderFixer.php
- app/Fixers/LaravelPhpdocSeparationFixer.php
- app/Fixers/Utils/PhpdocTagComparator.php
- app/Fixers/Utils/PhpdocTagComperator.php
- resources/presets/laravel.php
Fixes #1 
The Laravel Code Style has the following style throughout the source code, which currently can not be described with PHP-CS-Fixer alone. This PR adds three new custom fixers for the laravel preset, which of course can be added to psr12 or symfony if the user wants to.
The Fixers are mostly copies with changes from the PHP-CS-Fixer Source Code.
After `@param` should be two spaces then a `type-hint` then another two spaces and then the `$variable`
```diff
/**
* Here is a description for what the function does
-  * @param string $foo
+  * @param  string  $foo
* @return string
*/
public function bar($foo) {}
```
First should be the `description` after that `@param` then `@return` and at last `@throws`
The default rule `phpdoc_order` has a different order: `description`, `@param`, …
> [0.x] Add Fixers for Laravel specific PHPDocs

- app/Factories/ConfigurationFactory.php
This small PR remove unused `$path` variable from `Factories\ConfigurationFactory.php`.
> Remove unused $path variable

- resources/presets/laravel.php
This PR address the `list_syntax` rule.
`list()` is not used anywhere in the Laravel code base while the shortened syntax is. Adding this rule not only conforms to the existing Laravel syntax usage, but ensures other code bases using Pint conform to that syntax as well.
For reference: [PHPCS list_syntax](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.8|fixer:list_syntax)
> List syntax rule

- resources/presets/laravel.php
- tests/Feature/Fixers/BinaryOperatorSpacesFixerTest.php
- tests/Fixtures/fixers/binary_operator_spaces.php
This PR addresses the `binary_operator_spaces` rule.
Double arrows `=>` do not use extra spaces anywhere in the codebase. This is even more visible when checking at arrays, where none of the items are aligned, or for arrow function syntax.
> Also ensure that the double arrow has a single space on each side.

- app/Repositories/ConfigurationJsonRepository.php
- tests/Feature/ConfigurationTest.php
- tests/Fixtures/with-invalid-configuration/pint.json
This pull request checks if the configuration is valid, before actually use it.
Fixes #84
> [1.x] Ensures the configuration file is valid

- resources/presets/laravel.php
This PR updates the `method_argument_space` rule in the Laravel preset.
Currently, when having arguments on multiple lines, Pint doesn't enforce all arguments to be on its own line. I couldn't find any cases where the old formatting behavior is used in a new Laravel project. That's why I think it's better to use the default PHP CS Fixer value for this rule.
> [1.x] Update `method_argument_space rule` in Laravel preset

- resources/presets/laravel.php
This PR addresses an implied syntax rule of framework for the `continue` keyword.
When `continue` does not follow a control structure, a blank line is used to provide some breathing room.
[Illuminate\Auth\Access\Gate](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Auth/Access/Gate.php#L549-L551)
```php
if (! $this->canBeCalledWithUser($user, $before)) {
continue;
}
```
[Illuminate\Collections\Arr](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Collections/Arr.php#L275-L279)
```php
if (static::exists($array, $key)) {
unset($array[$key]);
continue;
}
```
For reference (see Example 3): [PHPCS blank_line_before_statement](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.8|fixer:blank_line_before_statement)
> [1.x] Laravel Preset - include `continue` in `blank_line_before_statement`

- app/Factories/ConfigurationFactory.php
This pull request makes `pint` to ignore the `build` folder by default. Usually, this folder is used for `.phar` files that don't actually need any kind of lint.
> [1.x] Ignores `build` folder by default

- composer.json
- composer.lock
- resources/presets/laravel.php
Release: https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.11.0
Deprecated Rules:
- https://cs.symfony.com/doc/rules/control_structure/no_trailing_comma_in_list_call.html
- https://cs.symfony.com/doc/rules/array_notation/no_trailing_comma_in_singleline_array.html
> Update to PHP-CS-Fixer v3.11

- .gitignore
- app/Factories/ConfigurationResolverFactory.php
- app/Repositories/ConfigurationJsonRepository.php
By default Pint creates a cache file in the /tmp directory of the system. This directory is cleared on reboot (at least on Linux). For some larger repositories, this means that the first run after a reboot is significantly longer.
I was previously using php cs fixer with a cache file in the root of the project (excluded via a gitignore).
This update allows you to have the cache file at the root of a project again.
```
{
"cache-file": ".pint.json"
}
```
> add configuration option to overwrite cache file location

- .github/workflows/publish-phar.yml
In #92 the action used to upload the phar was changed to `actions/upload-artifact`. This action only uploads the files as a build artifact, not to releases.
This PR adds a step to upload the phar to the release also.
> Fix publishing phar to releases

- .github/workflows/publish-phar.yml
Currently, the `publish-phar.yml` workflow is run thrice on each release.
https://github.com/laravel/pint/actions/workflows/publish-phar.yml
This PR limits it to run only when the release is "created".
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
> Run release workflow only on created event

- app/Commands/DefaultCommand.php
- app/Factories/ConfigurationResolverFactory.php
- app/Support/Git.php
- app/Support/Project.php
- storage/framework/cache/.gitignore
- tests/Feature/DirtyTest.php
- tests/Pest.php
This introduces a `--dirty` option to only run `pint` against _changed_ files.
**Motivation** 
Yes, this could be done with other tools. However, that requires intimate knowledge of Git and system commands, as well as some kind of automated runner (e.g. `pre-commit` hook).
Since `pint` is a CI tool, having this built-in provides an out-of-the-box solution to this common developer use case. While not the primary motivation, it also improves performance by running against a subset of files.
**Caveats**
- This has an underlying requirement of the project being within a Git repository. If used outside of a Git repository, an error is output.
- When `--dirty` is used, the `path` argument is ignored. I consider these two use cases mutually exclusive. However, a possible use case may exist where …
> Introduce `--dirty` for Git projects

- resources/presets/laravel.php
This pull request should ideally target an new version of Laravel Pint, that should ship by default in Laravel 10.x. Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.
> [1.x] Removes superfluous annotations

- .github/workflows/tests.yml
- composer.json
- composer.lock
This pull request accomplishes three tasks:
- Upgrades Pint 1 to Laravel Zero 10.
- Removes support for PHP 8.0, **limiting Pint (up to) to version 1.5.0 for applications using Laravel 9**, as Pint 1.6.0 will not support PHP 8.0.
- Resolves an internal issue preventing us from building the Pint binary with PHP 8.2.
> [1.x] Migrates to Laravel Zero 10

- .github/workflows/publish-phar.yml
This PR
1) Updates the PHP version in the `publish-phar` workflow to PHP 8.1.
2) Add support to run the `publish-phar` workflow with `workflow-dispatch` event.
> Improve workflow to publish the phar to the release.

- resources/presets/laravel.php
This pull request
💁‍♂️ For reference, see https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.15.1/doc/rules/class_notation/self_static_accessor.rst.
I have noticed use of `static` inside classes declared as `final` in
- https://github.com/pestphp/pest/blob/f52d4392a60456ba383636f2731e03b4eea796c6/src/Support/Arr.php#L76
- https://github.com/pestphp/pest/blob/f52d4392a60456ba383636f2731e03b4eea796c6/src/Expectation.php#L67
- https://github.com/pestphp/pest/blob/f52d4392a60456ba383636f2731e03b4eea796c6/src/Support/Reflection.php#L45
- https://github.com/pestphp/pest/blob/f52d4392a60456ba383636f2731e03b4eea796c6/src/Support/Reflection.php#L75
so perhaps it makes sense to enable the fixer for all users of the `laravel` preset instead of fixing these issues manually?
> Enhancement: Enable self_static_accessor fixer

- app/Repositories/GitPathsRepository.php
This pull request fixes `--dirty` detection of subfolders on Ubuntu. Closes https://github.com/laravel/pint/issues/160
> [1.x] Fixes `--dirty` detection of subfolders on Ubuntu

- .github/ISSUE_TEMPLATE/1_Bug_report.yml
I found an unnecessary line in 1_Bug_report.yml and removed it.
> remove unnecessary line in 1_Bug_report.yml

- resources/presets/laravel.php
PHP-CS-Fixer Rule: [type_declaration_spaces](https://cs.symfony.com/doc/rules/whitespace/type_declaration_spaces.html)
With the given configuration this will change it like this (Taken from the PHP-CS-Fixer Page):
```diff
--- Original
+++ New
<?php
class Bar
{
-    private string    $a;
-    private bool   $b;
+    private string $a;
+    private bool $b;
-    public function __invoke(array   $c) {}
+    public function __invoke(array $c) {}
}
```
> Add Rule: type_declaration_spaces

- resources/presets/laravel.php
PHP-CS-Fixer Rule: [nullable_type_declaration](https://cs.symfony.com/doc/rules/language_construct/nullable_type_declaration.html) 
With the given configuration this will change it like this (Taken from the PHP-CS-Fixer Page):
```diff
--- Original
+++ New
<?php
-function bar(null|int $value, null|\Closure $callable): void {}
+function bar(?int $value, ?\Closure $callable): void {}
```
```diff
--- Original
+++ New
<?php
class ValueObject
{
-    public null|string $name;
+    public ?string $name;
public ?int $count;
-    public null|bool $internal;
-    public null|\Closure $callback;
+    public ?bool $internal;
+    public ?\Closure $callback;
}
```
> Add Rule: nullable_type_declaration

- resources/presets/laravel.php
PHP-CS-Fixer Rule: [`nullable_type_declaration_for_default_null_value`](https://cs.symfony.com/doc/rules/function_notation/nullable_type_declaration_for_default_null_value.html)
With the given configuration this will change it like this (Taken from the PHP-CS-Fixer Page):
```diff
--- Original
+++ New
<?php
-function sample(?string $str = null)
+function sample(string $str = null)
{}
```
```diff
--- Original
+++ New
<?php
-function sample(string|int|null $str = null)
+function sample(string|int $str = null)
{}
```
```diff
--- Original
+++ New
<?php
-function sample((\Foo&\Bar)|null $str = null)
+function sample(\Foo&\Bar $str = null)
{}
```
This rule is currently not enforced in `laravel/framework` repository, but I saw some comments in PR's were it was said that the question mark should …
> Add Rule: nullable_type_declaration_for_default_null_value

- composer.json
- composer.lock
This pull request fixes the build on windows by using LZ 10.1.1. As LZ 10.1.1 reverts the box's version from 4.3.x to 4.2.x.
> [1.]x Fixes build on windows by using LZ 10.1.1

- resources/presets/laravel.php
PHP-CS-Fixer Rule: [function_typehint_space](https://cs.symfony.com/doc/rules/function_notation/function_typehint_space.html)
This rule is deprecated and superseded by [type_declaration_spaces](https://cs.symfony.com/doc/rules/whitespace/type_declaration_spaces.html).
Since we have added the type_declaration_spaces rule in https://github.com/laravel/pint/pull/194,
we can safely remove this rule.
https://github.com/laravel/pint/blob/07a28868cb59448b6ab1365dfb0f09e02cda8f9b/resources/presets/laravel.php#L195
> Remove deprecated function_typehint_space rule

- app/Output/SummaryOutput.php
- resources/presets/laravel.php
Using Laravel Promps, Volt, and potentially upcoming projects, we might find ourselves utilizing functional APIs through namespaced functions. Today, with the usage of Pint, users will end up with imports like this:
```php
<?php
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;
use function Laravel\Prompts\confirm;
use function Laravel\Prompts\multiselect;
use function Laravel\Prompts\select;
use RuntimeException;
use Symfony\Component\Console\Command;
use Symfony\Component\Console\Input\InputInterface;
class InstallCommand extends Command
{
// ...
}
```
So, in order to get things a little bit more organized "visually", this pull request proposes organizing these imports by "type". In other words, classes come first, and then, after a new line, the namespaced functions. …
> [1.x] Improves imports when using `functions`

- resources/presets/laravel.php
This pull request makes Pint's Laravel preset order interfaces and traits:
```diff
-new class implements B, A
+new class implements A, B
{
-   use B, A;
+   use A, B;
// ...
```
> [1.x] Orders interfaces and traits

- resources/presets/laravel.php
PHP-CS-Fixer Rule: [yoda_style](https://cs.symfony.com/doc/rules/control_structure/yoda_style.html)
This PR enfoce non-yoda-style
> Add rule: `yoda_style` to Laravel

- resources/presets/laravel.php
Because support for implicit support for implicit nullability exists only for backwards compatibility reasons and will be removed in the future. See https://github.com/laravel/pint/issues/235.
> Change default for nullable_type_declaration_for_default_null_value

- .github/workflows/tests.yml
- composer.json
- composer.lock
- config/commands.php
- resources/presets/laravel.php
Replaces https://github.com/laravel/pint/pull/232
> [1.x] Bump Dependencies and run Tests on skeleton

- composer.json
- composer.lock
Fixes a bug which occurred with PHP-CS-Fixer `3.47.0`.
See https://github.com/laravel/pint/pull/242#issuecomment-1901015357
I tested that with the bumped version the error does no longer occur.
cc: @phh
> Bump Dependencies

- app/Commands/DefaultCommand.php
- app/Providers/RepositoriesServiceProvider.php
- app/Repositories/ConfigurationJsonRepository.php
- tests/Feature/PresetTest.php
- tests/Fixtures/no-config/pint.json
- tests/Fixtures/no-config/with-fixes-based-on-config.php
Currently, `pint` will merge any project config with the `--preset` option. This was slightly unexpected and makes it difficult to quickly use one of the presents from within a project that has a custom `pint.json` config.
You can get around this by passing an invalid path to `--config`. But that's a bit hacky. I felt a `--no-config` option was nice and provides an explicit way to prevent `pint` from merging any project config.
For example, to apply the `laravel` preset to a set of stub files:
```sh
pint --no-config --preset laravel -- stubs
```
This is indeed a real world use case where a project has it's own rules configured within `pint.json`, but contains stub files which are formatted to the `laravel` preset.
> Add `--no-config` option

- app/Commands/DefaultCommand.php
- app/Factories/ConfigurationResolverFactory.php
Hi,
We have a internal bundle that defined the code style for all our projects. This bundle is therefore shared by multiple projects. 
We need to have the possibility to define, by project, the path of the pint cache file.
This pull request allow the user to do it by given the path of the cache file in the command line.
> Add the possibility to override the cache file path in command line

- app/NodeSandbox.php
- app/Prettier.php
- pint.json
Fixes tests on the Laravel skeleton and fix static analysis.
> [feat/blade] Fix tests for the laravel skeleton

- app/Actions/ElaborateSummary.php
- app/Commands/DefaultCommand.php
- tests/Feature/RepairTest.php
- tests/Feature/WithExitStatusTest.php
This adds a small feature, `--with-exit-status` that will exit with either 1 or 0 if there are changed files or not. Essentially this is the same as running with the `--test` flag except that it _also_ changes the files.
This is helpful for tools such as Captain Hook (or really any pre-commit hook) which rely on the exit code to know if there were changes, so that it will fail and allow amending the commit manually.
it should be noted that while it seems the prevailing consensus is that you should just run `pint` and then automatically add the changed files to the commit, however if you have additional working changes (e.g. you only staged part of the file, _or_ made changes after staging it) then those changes would now be inadvertently included in the commit.
Happy to add tests if this …
> feat: Add a --with-exit-status flag

- app/Factories/ConfigurationFactory.php
- composer.json
- composer.lock
With the release of PHP-CS-Fixer v3.57.0 it is possible to run the process in parallel.
I would like to try it out with pint. (But I can't build the binary for some reason).
This PR enables parallel execution by default and bumps the dependencies accordingly. I think if there should be a "breaking" change, that a simple revert of this PR would be enough.
Also not sure how this would affect the PR https://github.com/laravel/pint/pull/256 by @nunomaduro
> [1.x] Enable Parallel Execution

- resources/presets/empty.php
For a dirty big project, it is not possible to reformat all at once, but rather we need to apply rule by rule and make small PRs that are easy to review and merge.
Currently, I find no way to apply only a single rule on the project and avoid all the other rules.
This way we incrementally add rules to the pint.json in each PR and apply the modification on the entire project.
```json
{
"preset": "empty",
"rules": {
"no_empty_comment": true
}
}
```
> Create empty preset

- app/Actions/ElaborateSummary.php
- app/Factories/ConfigurationFactory.php
- app/Factories/ConfigurationResolverFactory.php
- app/Output/ProgressOutput.php
- app/Providers/AppServiceProvider.php
- app/ValueObjects/Issue.php
- resources/presets/laravel.php
- tests/Feature/DirtyTest.php
- tests/Feature/PresetTest.php
- tests/Feature/RepairTest.php
- tests/Feature/SummaryTest.php
- tests/Fixtures/without-issues-laravel/file.php
- tests/Fixtures/without-issues/file.php
This PR adds the rule `new_with_parentheses` to the Laravel preset with the configuration. It's a followup for https://github.com/laravel/pint/issues/284. The PR also runs Pint with the new rule over it's own codebase.
In after this change, running Pint with the Laravel Preset will make sure empty parentheses `()` will be removed from class Instantiations. 
```php
// the following line ...
$item = new Item();
// will become
$item = new Item;
```
> Laravel preset class parentheses

- phpstan.neon
When the following steps were followed to run phpstan, a deprecated warning was displayed.
So I remove deprecated config option of phpstan.neon.
```
composer install
./vendor/bin/phpstan --memory-limit=2G
Note: Using configuration file /xxx/pint/phpstan.neon.
⚠️  You're using a deprecated config option checkGenericClassInNonGenericObjectType ⚠️️
It's strongly recommended to remove it from your configuration file
and add the missing generic typehints.
If you want to continue ignoring missing typehints from generics,
add missingType.generics error identifier to your ignoreErrors:
parameters:
ignoreErrors:
-
identifier: missingType.generics
27/27 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
[OK] No errors  
```
> remove deprecated config option of phpstan

- app/Factories/ConfigurationResolverFactory.php
I discovered a bug where the rules written in the rules section are not applied when the following settings are written in pint.json:
```json
{
"preset": "empty",
"rules": {
"array_syntax": true
}
}
```
I made a fix because `ConfigurationFactory::preset([])` is not called unless "empty" is added to the available presets.
I tried writing the following code and compared the cases where "empty" is not present in $presets and where it is present:
```php
$example = array();
```
When "empty" is not present:
```shell
❯ ./pint -v --preset=empty --test
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
> Rules are not applied when "empty" is specified for the preset

- resources/presets/per.php
Hi,
`@PER` rule set is deprecated and will be removed in the next major version.
You should use `@PER-CS` instead.
> [1.x] Rename rule set `@PER` to `@PER-CS`

- resources/presets/laravel.php
- tests/Feature/Fixers/PhpUnitCasingTest.php
- tests/Fixtures/fixers/phpunit_method_casing.php
The Laravel preset should have an opinion on testsuite method casing.
There is always overhead involved working out what casing the testsuite is using. Often there can be multiple casings within a single testsuite. Even in our own ecosystem's packages, when contributions come from different people, we can see different casings within the one project.
The Laravel framework ships with snake casing, so I am proposing we stick with that and never have to waste brain cycles on this again for PHPUnit based testsuites.
> [1.x] Enforce `snake_case` methods for PHPUnit method in Laravel preset

- app/Output/Concerns/InteractsWithSymbols.php
- app/Output/ProgressOutput.php
- app/Output/SummaryOutput.php
- composer.json
- composer.lock
Use PHP-CS-Fixer `v3.65.0` and bump all other dependencies at the same time.
Due to a refactor of the runner / eventing system in https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8276 some changes were needed.
There were also some return type changes, which resulted in phpstan errors. It would be good if another person can take a further look at these changes.
> [1.x] PHP-CS-Fixer v3.56.0 compatibility

- resources/presets/laravel.php
This PR proposes to enable the [`single_line_comment_spacing`](//cs.symfony.com/doc/rules/comment/single_line_comment_spacing.html) fixer in the laravel preset.
> Add single_line_comment_spacing rule

- app/Commands/DefaultCommand.php
- app/Contracts/PathsRepository.php
- app/Project.php
- app/Repositories/GitPathsRepository.php
- tests/Feature/DiffTest.php
This PR is how I've always _wished_ the `--dirty` flag worked.
`pint --dirty` will lint _staged_ and _unstaged_ files (and possibly _untracked_?). But once a file is _committed_, it will not be touched again by `pint --dirty`, whether or not it passes. The only time it will be linted is when we run pint on the **whole** project again.
This _also_ means that running `pint --dirty` in CI is pointless, since all the files have already been *committed*, meaning we'll lint **nothing**. But running Pint without any flags can take upto **five minutes** in a large project, and that feedback cycle **sucks**.
`pint --diff=main` will collect **all** committed, staged, unstaged, and untracked files that **differ from the provided branch**. Meaning that if we've got a PR that only touches 5 files, we …
> [1.x] Adds `--diff` option

- resources/presets/laravel.php
This PR serves as a QoL for PHPStorm users, as well as for situations where you might accidentally import a class as it's own name: https://cs.symfony.com/doc/rules/import/no_unneeded_import_alias.html
> Add `no_unneeded_import_alias` rule

- app/Repositories/GitPathsRepository.php
- **Fix for #327**
`/\R+/` matches any type of line break, including:
- `\n` (LF - Unix/Linux)
- `\r\n` (CRLF - Windows)
- `\r` (CR - old macOS)
- Other uncommon variations
`PREG_SPLIT_NO_EMPTY`: Prevents empty elements in the result when consecutive line breaks are found
**NOTE:** Same as dirty
https://github.com/laravel/pint/blob/7afe4d284ef782dbbaf3c6a08d813ef8beab4e1f/app/Repositories/GitPathsRepository.php#L41
> Split files based on `/\R+/` regex for `--diff`, same as `--dirty`

- .github/workflows/publish-phar.yml
> Fix GitHub Action failing 'Publish the released PHAR' due to deprecated action 'actions/upload-artifact'

- app/Repositories/ConfigurationJsonRepository.php
- tests/Fixtures/extend/base.json
- tests/Fixtures/extend/pint.json
- tests/Fixtures/extend_recursive/base.json
- tests/Fixtures/extend_recursive/config.json
- tests/Fixtures/extend_recursive/pint.json
- tests/Unit/Repositories/ConfigurationJsonRepositoryTest.php
I have a use case where my company uses a global pint config, this work fine if the config doesn't need to change per project, but if we need to have project specific configuration, it becomes impossible to have them isolated.
It partially solves #174 
I purposefully chose to only allow 1 extend to avoid recursion issues (though it could be fixed through a fixed set of extent)
> Feature allow configuration extension from a different base file

- composer.json
- composer.lock
PHP-CS-Fixer now fully supports PHP 8.4 since the version 3.80.0
See their release at https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/tag/v3.80.0
Closes #317
Closes #324
Closes #326
Closes #336
Closes #342
Closes #352
Closes #354
Closes #368
> Full PHP 8.4 Support by PHP-CS-Fixer

- app/Commands/DefaultCommand.php
- tests/Feature/StdinTest.php
Hello!
Resolves https://github.com/laravel/pint/issues/262, resolves https://github.com/laravel/pint/issues/162
There's tools and editors (e.g., zed, https://jj-vcs.github.io/jj/latest/cli-reference/#jj-fix) that can integrate with formatters if the formatter accepts input on stdin and outputs the changes on stdout. This PR adds that functionality to pint
CC: @TheBlckbird, @bilogic, @serbanrobu, @gabrielbidula
Thanks!
> feat: add support for formatting code from stdin

- composer.json
- composer.lock
- resources/presets/laravel.php
A minor version bump to v3.88.2 with the addition of a name change to a rule in **resources/presets/laravel.php**.
The **visibility_required** rule was deprecated in favor of the **modifier_keywords** rule in PHP-CS-Fixer v3.88. From what I can see it's just a change to the rule name with the configuration and function of the fixer remaining the same.
There is a proxy in PHP-CS-Fixer that maintains compatibility with rule sets using the **visibility_required** name so pint users that use it in a custom configuration should be fine. Even so, I have altered the laravel ruleset since it is deprecated.
For reference, the PR to PHP-CS-Fixer that introduced the change: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/8995.
> Update PHP-CS-Fixer to v3.88.2.
